// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEc9_U61DUd5k3bcRmOqMmMhwdxB79yY0',
    appId: '1:454886444535:web:2400397cdc9a286493b2f2',
    messagingSenderId: '454886444535',
    projectId: 'madact17',
    authDomain: 'madact17.firebaseapp.com',
    storageBucket: 'madact17.firebasestorage.app',
    measurementId: 'G-PX4CBQKN5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANcAdwAf4zintG82jpEvvqr0nbEftYFQ8',
    appId: '1:454886444535:android:7b775ee8bc43dd8f93b2f2',
    messagingSenderId: '454886444535',
    projectId: 'madact17',
    storageBucket: 'madact17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ0dcZudU-TosISUGQXTqZl92-c-7ad3M',
    appId: '1:454886444535:ios:23cea6e715fb706b93b2f2',
    messagingSenderId: '454886444535',
    projectId: 'madact17',
    storageBucket: 'madact17.firebasestorage.app',
    iosBundleId: 'com.example.act17',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ0dcZudU-TosISUGQXTqZl92-c-7ad3M',
    appId: '1:454886444535:ios:23cea6e715fb706b93b2f2',
    messagingSenderId: '454886444535',
    projectId: 'madact17',
    storageBucket: 'madact17.firebasestorage.app',
    iosBundleId: 'com.example.act17',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEc9_U61DUd5k3bcRmOqMmMhwdxB79yY0',
    appId: '1:454886444535:web:66d63351fdeee97193b2f2',
    messagingSenderId: '454886444535',
    projectId: 'madact17',
    authDomain: 'madact17.firebaseapp.com',
    storageBucket: 'madact17.firebasestorage.app',
    measurementId: 'G-MTSVLF4QTN',
  );
}
